In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_stata('./data/voter_location2000_with_cov.dta')

In [3]:
full_data = data[data['_merge'] == 'matched (3)']

In [4]:
data_clean = full_data[['countyemsid','bctcb2000','lastname','firstname','birthdate','gender']]

In [6]:
data_clean.describe()

       countyemsid    bctcb2000   lastname firstname birthdate   gender
count      3156814      3156814    3156814   3156814   3156814  3156814
unique     3156814        28976     361962    240977     32371        3
top      305776628  20462011009  RODRIGUEZ   MICHAEL  18500101        F
freq             1        10692      23312     36256      1246  1828104

In [7]:
data = data_clean

In [10]:
name = pd.read_csv('./data/surname_list/app_c.csv')

In [13]:
name = name.convert_objects(convert_numeric=True)

In [14]:
name = name[[u'name', u'prop100k', u'pctwhite', u'pctblack', u'pctapi', u'pctaian', u'pct2prace', u'pcthispanic']]

In [15]:
name.columns = ['name','perc','white','black','api','aian','2race','hispanic']

In [16]:
name['perc'] = name['perc']/10000
name['white'] = name['white'] / 100
name['black'] = name['black'] / 100
name['api'] = name['api'] / 100
name['2race'] = name['2race'] /100
name['hispanic'] = name['hispanic'] / 100

In [54]:
name_prob = name

In [18]:
len(data['lastname'].unique())

361962

In [19]:
alllastname = data['lastname']

In [23]:
diclastname = np.array(name['name'])

In [24]:
intlastname = np.in1d(alllastname, diclastname)

In [25]:
intlastname.sum()/float(len(alllastname)) # 83.98% of lastname are included in the surname list

0.83980620967849229

In [26]:
data_clean = data[intlastname] # pick out those rows having lastname included in the list

In [27]:
data_clean

        countyemsid    bctcb2000    lastname  firstname birthdate gender
0          0000000Y  50020011020      NASSAR      LINDA  19481215      F
2          00000116  50065001000      LICATA      MARIE  19270526      F
3          00000135  50226002037    BELANSKY      IRENE  19340129      F
4          00000167  41227014001    MOLINARI       CRUZ  19330914      F
6          00000254  50244001032       MARSH    WILLIAM  19291101      M
7          00000316  41275002010      SEIBEL    SANFORD  19340508      M
8          00000542  31126003003       BLAKE   VERONICA  19500213      F
10         00000619  10212001001      TAYLOR    BERNARD  19220903      M
11         00000717  50125002005     MORRELL    PHYLLIS  19210123      F
12         00001021  10174012001     JENKINS        JOE  19270612      M
13         00001066  50006001017     GERHARD      EDITH  19210329      F
14         00001076  50065001000      LICATA    MICHAEL  19230129      M
15         00001094  41333002004     GROPPER        LEO  19180730      M
17         00001366  50156014012       FARGO    THERESA  19261026      F
18         00001384  50291021013        BRAY    CHARLES  19241025      M
19         00001399  50047001003      WINTER    DOROTHY  19220302      F
20         00001400  50047001003      WINTER   WINFIELD  19191130      M
21         00001414  40661001006     HASLACH    CHARLES  19310809      M
22         00001716  50151005007     TROIANO    ANTHONY  19290719      M
23         00001725  50169011008     MCGRATH      HELEN  19250818      F
24         00001741  50291042004    LOMBARDI  SALVATORE  19250713      M
25         00001778  50189011005      DEMAIO    ANTHONY  19260910      M
26         00001998  50187012001    CORRIGAN       JOHN  19271008      M
28         00002138  50187021011  BIRMINGHAM    FRANCIS  19270618      M
29         00002292  50147003004     CASSIDY     GLADYS  19221128      F
30         00002365  50189011005      DEMAIO       MARY  19290210      F
32         00002513  41207001013   MCDERMOTT   WINIFRED  19290329      F
33         00002517  50244004029     JOHNSEN      DORIS  19200620      F
34         00002674  50244001000      CONROY    DOLORES  19240328      F
35         00002795  50244001032       MARSH       MARY  19301012      F
...             ...          ...         ...        ...       ...    ...
3156781   ZZ0434682  30874012002    MCINTOSH     STACEY  19630824      M
3156782   ZZ0434686  30874012002       JONES     DAPHNE  19301116      F
3156783   ZZ0434698  30906003001       WYLIE   TRANCINE  19660410      F
3156784   ZZ0434725  30764003003       TOWNS     WARREN  19340619      M
3156785   ZZ0434732  30518001001       SOHAN     RONALD  19470128      M
3156786   ZZ0434738  30764001001     SHUSTER    GILBERT  19561006      M
3156787   ZZ0434740  30510003000       BAKER     YVONNE  19510205      F
3156788   ZZ0434741  30514001002       ANGEL    FRANKIE  19491225      M
3156789   ZZ0434748  30462011000    VENTRICE    MAUREEN  19620324      F
3156790   ZZ0434753  30462011000      DUBOFF       ROSE  19190519      F
3156791   ZZ0434769  30484001004        OMAR      SIHAM  19410210      F
3156792   ZZ0434779  30520003001       FEDER       SIMA  19250626      F
3156793   ZZ0434784  30133001000      GODWIN       RUBY  19440429      F
3156794   ZZ0434788  30157004001       PRYCE    PATRICK  19560907      M
3156795   ZZ0434794  30207003001        NELL   ANNMARIE  19471204      F
3156796   ZZ0434799  30165004001      KRAMER      SUSAN  19520815      F
3156797   ZZ0434807  30502011005       MOSCA    MICHAEL  19540904      M
3156798   ZZ0434809  30190001002      CLEARY     THOMAS  19540310      M
3156799   ZZ0434816  31106001003  BOCHICCHIO       PAUL  19650222      M
3156800   ZZ0434820  30496001002      EDMOND     WILLIE  19331028      M
3156801   ZZ0434831  30506004001     ROBERTS       IONA  19181116      F
3156803   ZZ0434852  30762003000     POLANCO    XIOMARA  19660221      F
3156804   ZZ0434855  30532001000       EVANS       ANNE  19460123      F
3156805   ZZ0434866  30490001001      MILLER     GEORGE  19290118      M
3156806   ZZ0434880  30482001002     AGUIRRE        EVA  19540525      F
3156807   ZZ0434888  30157003000     KOEHLER     SHERRY  19401008      F
3156808   ZZ0434908  30458001001    RICHLAND     STEVEN  19491228      M
3156809   ZZ0434922  30702013006       COHEN    ISIDORE  19310423      M
3156810   ZZ0434927  30594013002   BERARDINO      MARIA  19640520      F
3156811   ZZ0434931  30594013002       APICE    THERESA  19351002      F

[2651112 rows x 6 columns]

In [28]:
df = pd.read_csv('./data/Census2000_BG/C2000_R10950075_SL150.csv',dtype=object)

In [29]:
df = df[['SE_T015_001','SE_T015_003','SE_T015_004','SE_T015_005','SE_T015_006','SE_T015_007','SE_T015_008','SE_T015_009','SE_T015_010','Geo_TRACT','Geo_BLKGRP','Geo_COUNTY']]

In [30]:
df['borocode'] = ''

In [31]:
df.loc[df['Geo_COUNTY'] == '047','borocode'] = '3'
df.loc[df['Geo_COUNTY'] == '081','borocode'] = '4'
df.loc[df['Geo_COUNTY'] == '061','borocode'] = '1'
df.loc[df['Geo_COUNTY'] == '005','borocode'] = '2'
df.loc[df['Geo_COUNTY'] == '085','borocode'] = '5'

In [32]:
df['cbg2000'] = ''

In [33]:
df.loc[:,'cbg2000'] = df.loc[:,'borocode']+df.loc[:,'Geo_TRACT'] + df.loc[:,'Geo_BLKGRP']

In [34]:
df.columns = ['total','white','black','indian_alaska','asian','hawaiian_islander','other','2ormore','hispanic','TRACT','BLKGRP','COUNTY','borocode','cbg2000']

In [35]:
df = df[['cbg2000','total','white','black','indian_alaska','asian','hawaiian_islander','other','2ormore','hispanic','TRACT','BLKGRP','COUNTY']]

In [36]:
df[['total','white','black','indian_alaska','asian','hawaiian_islander','other','2ormore','hispanic']] = df[['total','white','black','indian_alaska','asian','hawaiian_islander','other','2ormore','hispanic']].astype(float)

In [37]:
df.loc[:,'asian'] = df.loc[:,'asian'] + df.loc[:,'hawaiian_islander']

In [38]:
df = df.drop('hawaiian_islander',1)
df = df.drop('other',1)
df = df.drop(['TRACT','BLKGRP','COUNTY'],1)

In [40]:
df.columns = ['cbg2000','total','white','black','aian','api','2race','hispanic']

In [41]:
df = df[['cbg2000','total','white','black','api','aian','2race','hispanic']]

In [42]:
df['white'] = df['white']/df['total']

In [43]:
df['black'] = df['black']/df['total']
df['api'] = df['api']/df['total']
df['aian'] =df['aian']/df['total']
df['2race'] =df['2race']/df['total']
df['hispanic'] = df['hispanic']/df['total']

In [47]:
df['total'].sum()

18976457.0

In [48]:
df['perc'] = df['total']/df['total'].sum()

In [51]:
location_prob = df

In [52]:
location_prob

,cbg2000,total,white,black,api,aian,2race,hispanic,perc
0,0001001,1031,0.401552,0.491756,0.030068,0.000000,0.033948,0.037827,0.000054
1,0001002,697,0.385940,0.476327,0.025825,0.001435,0.030129,0.078910,0.000037
2,0002001,2534,0.127072,0.739148,0.023283,0.001579,0.028414,0.079716,0.000134
3,0002002,730,0.128767,0.742466,0.023288,0.000000,0.038356,0.065753,0.000038
4,0002003,1436,0.114903,0.766713,0.020891,0.000000,0.023677,0.073816,0.000076
5,0002004,791,0.156764,0.718078,0.006321,0.000000,0.053097,0.056890,0.000042
6,0003001,948,0.913502,0.043249,0.013713,0.000000,0.011603,0.017932,0.000050
7,0003002,4612,0.473330,0.404380,0.030139,0.001518,0.021899,0.065698,0.000243
8,0004011,2127,0.862247,0.067701,0.029149,0.001881,0.008933,0.028679,0.000112
9,0004031,1252,0.822684,0.055112,0.062300,0.000799,0.020767,0.034345,0.000066
10,0004032,1453,0.860289,0.055747,0.028906,0.003441,0.026153,0.024776,0.000077
11,0004033,736,0.860054,0.081522,0.027174,0.000000,0.009511,0.020380,0.000039
12,0004034,545,0.783486,0.124771,0.044037,0.001835,0.012844,0.029358,0.000029
13,0004035,425,0.894118,0.051765,0.018824,0.000000,0.002353,0.032941,0.000022
14,0004041,4922,0.676148,0.126371,0.101178,0.000813,0.015238,0.076798,0.000259
15,0005011,1186,0.417369,0.437605,0.025295,0.002530,0.025295,0.090219,0.000062
16,0005012,813,0.634686,0.250923,0.011070,0.001230,0.039360,0.062731,0.000043
17,0005013,608,0.555921,0.286184,0.024671,0.006579,0.032895,0.092105,0.000032
18,0005014,899,0.656285,0.185762,0.047831,0.001112,0.044494,0.064516,0.000047
19,0005021,2064,0.803779,0.090601,0.039729,0.002907,0.014535,0.048450,0.000109
20,0005022,425,0.705882,0.141176,0.080000,0.002353,0.037647,0.025882,0.000022
21,0005023,1100,0.725455,0.153636,0.030909,0.006364,0.020909,0.061818,0.000058
22,0006001,706,0.354108,0.454674,0.031161,0.005666,0.043909,0.110482,0.000037
23,0006002,811,0.420469,0.395808,0.064118,0.000000,0.062885,0.056720,0.000043
24,0006003,1779,0.583474,0.228780,0.054525,0.001686,0.039910,0.088252,0.000094
25,0007001,855,0.162573,0.735673,0.019883,0.000000,0.039766,0.038596,0.000045
26,0007002,629,0.130366,0.788553,0.001590,0.009539,0.038156,0.031797,0.000033
27,0007003,512,0.128906,0.798828,0.005859,0.005859,0.035156,0.021484,0.000027
28,0007004,1098,0.165756,0.713115,0.011840,0.000911,0.027322,0.079235,0.000058
29,0007005,1045,0.160766,0.698565,0.031579,0.014354,0.031579,0.054545,0.000055
...,...,...,...,...,...,...,...,...,...
15049,9910001,894,0.989933,0.002237,0.001119,0.000000,0.002237,0.002237,0.000047
15050,9910002,951,0.961094,0.001052,0.007361,0.004206,0.011567,0.014721,0.000050
15051,9910003,1195,0.975732,0.003347,0.005021,0.001674,0.003347,0.010879,0.000063
15052,9910004,1144,0.988636,0.000874,0.001748,0.000000,0.002622,0.006119,0.000060
15053,9911001,803,0.975093,0.002491,0.001245,0.001245,0.014944,0.004981,0.000042
15054,9911002,1026,0.965887,0.002924,0.002924,0.013645,0.009747,0.004873,0.000054
15055,9911003,911,0.983535,0.003293,0.002195,0.001098,0.008782,0.001098,0.000048
15056,9901001,684,0.978070,0.000000,0.001462,0.000000,0.004386,0.016082,0.000036
15057,9901002,825,0.958788,0.001212,0.001212,0.001212,0.004848,0.032727,0.000043
15058,9901003,814,0.957002,0.017199,0.001229,0.003686,0.015971,0.004914,0.000043
15059,9901004,984,0.978659,0.005081,0.003049,0.000000,0.004065,0.009146,0.000052
15060,9901005,1188,0.972222,0.010101,0.001684,0.001684,0.005892,0.008418,0.000063
15061,9901006,1310,0.945038,0.012214,0.010687,0.000000,0.010687,0.021374,0.000069
15062,9902001,669,0.991031,0.000000,0.002990,0.000000,0.001495,0.004484,0.000035
15063,9902002,707,0.984441,0.004243,0.007072,0.000000,0.000000,0.004243,0.000037
15064,9902003,2720,0.975000,0.004779,0.002941,0.001103,0.007353,0.008088,0.000143
15065,9902004,1375,0.949091,0.008000,0.002909,0.003636,0.020364,0.015273,0.000072
15066,9903001,1408,0.965909,0.006392,0.003551,0.002131,0.007812,0.014205,0.000074
15067,9903002,1468,0.985014,0.002044,0.001362,0.001362,0.003406,0.006131,0.000077
15068,9903004,1181,0.981372,0.000847,0.002540,0.000847,0.007621,0.005080,0.000062
15069,9903005,1168,0.979452,0.006849,0.000856,0.000856,0.005993,0.005993,0.000062
15070,9904001,892,0.984305,0.001121,0.002242,0.000000,0.003363,0.008969,0.000047
15071,9904002,450,0.993333,0.002222,0.002222,0.000000,0.002222,0.000000,0.000024
15072,9904003,1247,0.972735,0.012029,0.004010,0.001604,0.003208,0.006415,0.000066
15073,9904004,610,0.977049,0.000000,0.006557,0.003279,0.001639,0.011475,0.000032
15074,9904005,776,0.975515,0.003866,0.005155,0.000000,0.009021,0.002577,0.000041
15075,9905001,725,0.991724,0.001379,0.000000,0.001379,0.001379,0.004138,0.000038
15076,9905002,1190,0.968067,0.007563,0.001681,0.002521,0.010924,0.007563,0.000063
15077,9905003,812,0.987685,0.000000,0.000000,0.000000,0.004926,0.007389,0.000043
15078,9905004,1418,0.986601,0.002821,0.000000,0.002116,0.004937,0.003526,0.000075

In [53]:
location_prob.to_csv('./data/location_prob.csv')

In [55]:
name_prob.to_csv('./data/name_prob.csv')

In [56]:
intlastname.sum()/float(len(alllastname))

0.83980620967849229

$$
P(R_i = r) = \sum_g P(R_i = r| G_i = g)P(G_i = g)
$$

In [80]:
white_perc = (location_prob['white'] * location_prob['perc']).sum() 
black_perc = (location_prob['black'] * location_prob['perc']).sum()
api_perc = (location_prob['api'] * location_prob['perc']).sum()
aian_perc = (location_prob['aian'] * location_prob['perc']).sum()
race_perc = (location_prob['2race'] * location_prob['perc']).sum()
hispanic_perc = (location_prob['hispanic'] * location_prob['perc']).sum()

In [81]:
white_perc

0.61976695649772773

In [82]:
black_perc

0.14821644525108138

In [83]:
api_perc

0.054865668549192295

In [84]:
aian_perc

0.0027665332891171415

In [85]:
race_perc

0.019293169425673086

In [86]:
hispanic_perc

0.15111266555184669

In [87]:
race_location_prob = location_prob.copy()

In [88]:
race_location_prob.loc[:,'white'] = location_prob.loc[:,'white'] * location_prob.loc[:, 'perc'] / white_perc
race_location_prob.loc[:,'black'] = location_prob.loc[:,'black'] * location_prob.loc[:, 'perc'] / black_perc
race_location_prob.loc[:,'api'] = location_prob.loc[:,'api'] * location_prob.loc[:, 'perc'] / api_perc
race_location_prob.loc[:,'aian'] = location_prob.loc[:,'aian'] * location_prob.loc[:, 'perc'] / aian_perc
race_location_prob.loc[:,'2race'] = location_prob.loc[:,'2race'] * location_prob.loc[:, 'perc'] / race_perc
race_location_prob.loc[:,'hispanic'] = location_prob.loc[:,'hispanic'] * location_prob.loc[:, 'perc'] / hispanic_perc

block2 contains $P(R_i =r | G_i = g)$

In [89]:
block2['white'].sum()

0.99999999999999989